<?php
echo "<!DOCTYPE html>\n"; 
echo "<html>\n"; 
echo "<title>Trivia Login</title>	\n"; 
echo "<link rel=\"stylesheet\" type=\"text/css\" href=\"css/loginLayout.css\" />	\n"; 
echo "<script type=\"text/javascript\" src =\"js/mainJS.js\"></script>\n"; 
echo "<body class=\"signin\">\n"; 
echo "<!--\n"; 
echo "<div class=\"topHead\">\n"; 
echo "	<a href=\"index.html\">Take me home!</a>\n"; 
echo "</div>\n"; 
echo "-->\n"; 
echo "<div id=\"content\">\n"; 
echo "	<div id=\"inner\">\n"; 
echo "		<h1 id=\"signinLogo\"><a href=\"index.html\"></a></h1>\n"; 
echo "		\n"; 
echo "		<div id=\"signinBlock\">\n"; 
echo "			<!--<h1>Eagan High School Trivia</h1>-->\n"; 
echo "			<span class=\"formContainer\">			    \n"; 
echo " 				<form id=\"signInForm\" action=\"login.html\" method=\"POST\">\n"; 
echo "					<span>\n"; 
echo "						<input class=\"fillin\" autofocus name=\"Username\" value=\"\" title=\"Username\" type=\"Username\" required placeholder=\"Username\" />\n"; 
echo "						<span class=\"message\"></span>\n"; 
echo "					</span>\n"; 
echo "					\n"; 
echo "					<span>\n"; 
echo "						<input class=\"fillin\" name=\"password\" title=\"Password\" type=\"password\" required placeholder=\"Password\" />\n"; 
echo "				\n"; 
echo "						<span class=\"message\"></span>\n"; 
echo "					</span>\n"; 
echo "				\n"; 
echo "					<div class=\"error\">\n"; 
echo "						<span class=\"message\"></span>\n"; 
echo "					</div>\n"; 
echo "\n"; 
echo "					<div class=\"buttonWrap\">\n"; 
echo "						<input type=\"hidden\" name=\"persist\" value=\"true\" />\n"; 
echo "						<input type=\"hidden\" name=\"returnTo\" value=\"/\" />\n"; 
echo "\n"; 
echo "						\n"; 
echo "\n"; 
echo "						<input class=\"button\" type=\"submit\" alt=\"Sign in!\" value=\"Let's Go\" />\n"; 
echo "					</div>\n"; 
echo "				</form>	\n"; 
echo "			</span>\n"; 
echo "		</div>\n"; 
echo "	</div>\n"; 
echo "</div>\n"; 
echo "	\n"; 
echo "	\n"; 
echo "</body>\n"; 
echo "\n"; 
echo "</html>\n";
?>